# Generated by Django 4.0.1 on 2022-04-26 06:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashmin', '0037_user_edit'),
    ]

    operations = [
        migrations.AlterField(
            model_name='noteform',
            name='subject',
            field=models.CharField(choices=[('DS', 'DS'), ('OS', 'OS'), ('DBMS', 'DBMS'), ('SE', 'SE'), ('DF', 'DF'), ('CN', 'CN'), ('C', 'C'), ('JAVA', 'JAVA'), ('PHP', 'PHP'), ('PYTHON', 'PYTHON'), ('C++', 'C++'), ('.NET', '.NET')], max_length=20),
        ),
        migrations.AlterField(
            model_name='noteform',
            name='title',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='videoform',
            name='subject',
            field=models.CharField(choices=[('DS', 'DS'), ('OS', 'OS'), ('DBMS', 'DBMS'), ('SE', 'SE'), ('DF', 'DF'), ('CN', 'CN'), ('C', 'C'), ('JAVA', 'JAVA'), ('PHP', 'PHP'), ('PYTHON', 'PYTHON'), ('C++', 'C++'), ('.NET', '.NET')], max_length=20),
        ),
        migrations.AlterField(
            model_name='videoform',
            name='title',
            field=models.CharField(max_length=20),
        ),
    ]
